import { config, library } from "@fortawesome/fontawesome-svg-core";
import {
  faAngleDown,
  faArrowRight,
  faArrowLeft,
  faArrowUpRightFromSquare,
  faCalendarDays,
  faBullseye,
  faCheck,
  faClock,
  faGlobe,
  faHeart,
  faHexagonNodes,
  faLayerGroup,
  faLocationDot,
  faMapLocationDot,
  faMicrophone,
  faPenNib,
  faPhone,
  faShareNodes,
  faBookmark,
  faRankingStar,
  faTriangleExclamation,
  faUser,
} from "@fortawesome/free-solid-svg-icons";

config.autoAddCss = false;

library.add(
  faMicrophone,
  faAngleDown,
  faArrowRight,
  faArrowLeft,
  faArrowUpRightFromSquare,
  faBullseye,
  faCalendarDays,
  faCheck,
  faClock,
  faGlobe,
  faHeart,
  faHexagonNodes,
  faBookmark,
  faLayerGroup,
  faLocationDot,
  faMapLocationDot,
  faPenNib,
  faPhone,
  faRankingStar,
  faShareNodes,
  faTriangleExclamation,
  faUser,
);

export {
  faMicrophone,
  faAngleDown,
  faArrowRight,
  faArrowLeft,
  faArrowUpRightFromSquare,
  faBullseye,
  faCalendarDays,
  faCheck,
  faClock,
  faGlobe,
  faHeart,
  faHexagonNodes,
  faBookmark,
  faLayerGroup,
  faLocationDot,
  faMapLocationDot,
  faPenNib,
  faPhone,
  faRankingStar,
  faShareNodes,
  faTriangleExclamation,
  faUser,
};
